### ISSUE TITLE
jquery.once for anonymous users

### ISSUE THREAD

**Issue by zsuffad** [medienverbinder/vegas#1]
Module need to add jquery.once as a dependencie into vegas.libraries.yml  in order to work for anonymous user too.

```
vegas.libraries.yml
```
```
@@ -3,6 +3,8 @@
   js:
     /libraries/vegas/dist/vegas.min.js: {}
     js/vegas.js: {}
+  dependencies:
+    - core/jquery.once
   css:
     theme:
       /libraries/vegas/dist/vegas.min.css: {}
```

**Comment by medienverbinder** [comment]
I've added the [dependencies](https://github.com/medienverbinder/vegas/commit/92ae7011f008670910dd1a63453cb83afee10cf9).

Thanks @zsuffad !
